{
  config,
  pkgs,
  lib,
  osConfig,
  ...
}:
# =============================================================================
# modules/home-manager/hyprland.nix — Hyprland config wiring (HOME half).
# =============================================================================
#
# The SYSTEM half (compositor enablement, portals, audio) is in
# modules/nixos/graphical.nix. THIS half is your Hyprland *configuration*.
#
# DESIGN FORK — how to manage Hyprland config, two routes:
#
#   ROUTE 1 (ACTIVE, tonybanters-style): keep hyprland.conf and its includes as
#   PLAINTEXT files under dotfiles/hypr/ and symlink them into ~/.config/hypr
#   with `mkOutOfStoreSymlink`. The symlink points at the file IN YOUR REPO
#   working tree (not the immutable /nix/store), so you can edit a keybind and
#   run `hyprctl reload` to see it INSTANTLY — no `nixos-rebuild`. This is the
#   best way to iterate on a rice. The tradeoff: these files aren't "pure" Nix
#   (they're plain conf), which is exactly why they're easy to hack on.
#
#   ROUTE 2 (ALTERNATIVE, declarative): express the whole config as Nix via
#   `wayland.windowManager.hyprland.settings = { ... }`. Fully reproducible and
#   type-checked, but every change needs a rebuild. Shown commented at the
#   bottom so you can compare and switch when the rice stabilizes.
let
  os = osConfig.fleet;

  # Absolute path to the plaintext hypr dotfiles IN THE REPO working tree.
  # `mkOutOfStoreSymlink` needs a path on the live filesystem, so we build it
  # from the home directory + the repo location. Adjust `repoDir` if you clone
  # this somewhere other than ~/code/nix-dotfiles/homelab-fleet.
  repoDir = "${config.home.homeDirectory}/code/nix-dotfiles/homelab-fleet";
  hyprSrc = "${repoDir}/dotfiles/hypr";
in
lib.mkIf os.graphical.enable {
  # ROUTE 1: symlink each hand-edited Hyprland file into place, editable live.
  # (colors.conf is NOT here — it's generated by theme.nix into the same dir.)
  xdg.configFile = {
    "hypr/hyprland.conf".source = config.lib.file.mkOutOfStoreSymlink "${hyprSrc}/hyprland.conf";
    "hypr/keybinds.conf".source = config.lib.file.mkOutOfStoreSymlink "${hyprSrc}/keybinds.conf";
    "hypr/looknfeel.conf".source = config.lib.file.mkOutOfStoreSymlink "${hyprSrc}/looknfeel.conf";
    "hypr/rules.conf".source = config.lib.file.mkOutOfStoreSymlink "${hyprSrc}/rules.conf";
  };

  # Packages the Hyprland session/keybinds expect (referenced from the conf).
  home.packages = with pkgs; [
    hyprpaper # wallpaper daemon
    hyprlock # screen locker
    hypridle # idle daemon
    grim # screenshot
    slurp # region select (grim + slurp = area screenshots)
    swaynotificationcenter # notifications (swaync) — saneaspect uses this too
    pavucontrol # audio GUI
    brightnessctl
    playerctl
  ];

  # Wallpaper via hyprpaper, driven by the shared option (if set). If the
  # option is null, hyprpaper just isn't given an image (Hyprland shows its
  # default background). Written declaratively here since it's simple.
  xdg.configFile."hypr/hyprpaper.conf" = lib.mkIf (os.theme.wallpaper != null) {
    text = ''
      preload = ${builtins.toString os.theme.wallpaper}
      wallpaper = ,${builtins.toString os.theme.wallpaper}
      splash = false
    '';
  };

  # ---------------------------------------------------------------------------
  # ROUTE 2 (ALTERNATIVE, declarative) — commented. Uncomment this block AND
  # remove the ROUTE 1 xdg.configFile symlinks above to manage Hyprland purely
  # in Nix. Note you'd then move keybinds/looknfeel into `settings` too.
  # ---------------------------------------------------------------------------
  # wayland.windowManager.hyprland = {
  #   enable = true;
  #   settings = {
  #     "$mod" = "SUPER";
  #     monitor = os.monitors;                 # from the shared option
  #     "$terminal" = "kitty";
  #     "$menu" = "wofi --show drun";
  #     bind = [
  #       "$mod, Return, exec, $terminal"
  #       "$mod, Q, killactive,"
  #       "$mod, D, exec, $menu"
  #       # ... etc. (mirror dotfiles/hypr/keybinds.conf)
  #     ];
  #     general = {
  #       gaps_in = 4;
  #       gaps_out = 8;
  #       border_size = 2;
  #     };
  #   };
  # };
}
