{
  config,
  pkgs,
  lib,
  osConfig,
  ...
}:
# =============================================================================
# modules/home-manager/theme.nix — ROUTE A: static base16 theming (omarchy-style).
# =============================================================================
#
# This module turns the chosen static theme (rocinante.theme.name) into concrete
# outputs:
#   * a GTK theme + cursor (dark/light per the theme's polarity)
#   * an exported palette other HM modules read (waybar/wofi/terminal), so all
#     apps share ONE source of truth
#   * the generated Hyprland colors file (dotfiles/hypr/colors.conf) written
#     from the palette (Nix drives the compositor's accent colors)
#
# It self-guards on the graphical toggle, so it's inert on tycho.
#
# ROUTE B note: when you switch to matugen (theme-matugen.nix), that module sets
# `rocinante.theme.matugen.enable = true` and this static path steps aside for
# the color-generation pieces (the matugen route writes its own colors). The
# GTK/cursor scaffolding here is harmless either way.
let
  os = osConfig.fleet;

  # Look up the active theme from the registry. `themes/default.nix` maps
  # name -> palette. This is where the enum in options.nix pays off: an invalid
  # name simply wouldn't be in the attrset.
  themes = import ../../themes;
  theme = themes.${os.theme.name};

  isDark = theme.meta.polarity == "dark";
in
lib.mkIf os.graphical.enable {
  # ---------------------------------------------------------------------------
  # Export the active palette so sibling modules (waybar/wofi/terminal/hyprland)
  # can read `config.fleet._resolvedTheme` without re-importing the registry.
  # We stash it under a private, underscore-prefixed key to signal "internal".
  # ---------------------------------------------------------------------------
  # NOTE: home-manager doesn't have our `rocinante` options namespace by default
  # here, so we expose the palette via a plain `home.sessionVariables`-free
  # mechanism: a passthrough attribute other modules import directly. To keep it
  # simple and avoid custom options in HM, sibling modules import the registry
  # themselves (see waybar.nix). This module focuses on GTK/cursor + colors.conf.

  # ---------------------------------------------------------------------------
  # GTK theme + icons + cursor. We use well-known theme packages and select
  # dark/light by polarity. (saneaspect uses an Everforest GTK theme; here we
  # keep it generic/adwaita-ish so any base16 choice looks coherent.)
  # ---------------------------------------------------------------------------
  gtk = {
    enable = true;
    theme = {
      name = if isDark then "Adwaita-dark" else "Adwaita";
      package = pkgs.gnome-themes-extra;
    };
    iconTheme = {
      name = "Adwaita";
      package = pkgs.adwaita-icon-theme;
    };
    cursorTheme = {
      name = "Adwaita";
      package = pkgs.adwaita-icon-theme;
      size = 24;
    };
  };

  # Make Qt apps follow the GTK look so the desktop is visually consistent.
  qt = {
    enable = true;
    platformTheme.name = "gtk";
  };

  # Cursor env for Wayland/XWayland consistency.
  home.pointerCursor = {
    name = "Adwaita";
    package = pkgs.adwaita-icon-theme;
    size = 24;
    gtk.enable = true;
  };

  # Prefer dark across GTK4/libadwaita apps when the theme is dark.
  dconf.settings = lib.mkIf isDark {
    "org/gnome/desktop/interface".color-scheme = "prefer-dark";
  };

  # ---------------------------------------------------------------------------
  # Generate the Hyprland colors file from the palette. This writes
  # ~/.config/hypr/colors.conf with $variables that hyprland.conf references.
  # This is the "Nix drives the theme" moment: change rocinante.theme.name,
  # rebuild, and the compositor's borders/accents update from the registry.
  #
  # We write it to the XDG path directly (NOT via the mkOutOfStoreSymlink that
  # the hand-edited hypr files use) because THIS file is generated, not
  # hand-edited. Hyprland reads both happily.
  # ---------------------------------------------------------------------------
  xdg.configFile."hypr/colors.conf".text = ''
    # AUTO-GENERATED by modules/home-manager/theme.nix from theme "${theme.meta.name}".
    # Do not edit by hand — change rocinante.theme.name and rebuild instead.
    $base00 = rgb(${theme.base00})
    $base05 = rgb(${theme.base05})
    $accent = rgb(${theme.accent})
    $red    = rgb(${theme.base08})
    $green  = rgb(${theme.base0B})
    $blue   = rgb(${theme.base0D})
    # Hyprland border colors (active uses accent->blue gradient, inactive dim).
    $activeBorder   = rgba(${theme.accent}ee) rgba(${theme.base0D}ee) 45deg
    $inactiveBorder = rgba(${theme.base03}aa)
  '';
}
